sudo: required
before_install: 
  - sudo apt-get install libva-dev git curl 
  - sudo mkdir -p /opt/openwebrtc-0.3
  - sudo chown -R $UID /opt/openwebrtc-0.3
  - git config --global user.email "@cybercypher"
  - git config --global user.name "@cybercypher"
script: 
  - mkdir build
  - cd build
  - git clone https://github.com/cybercypher/cerbero.git
  - cd cerbero
  - ./cerbero-uninstalled -c config/linux.cbc fetch-package --full-reset --reset-rdeps openwebrtc 
  - ./cerbero-uninstalled -c config/linux.cbc bootstrap
  - ./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc

